language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

git:
  submodules: false

warnings_are_errors: true

addons:
  apt:
    packages:
      - libudunits2-dev

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
